### ISSUE TITLE
[feature] support `json` as `ast-grep` configuration in playground

### ISSUE THREAD

**Issue by baiwusanyu-c** [ast-grep/ast-grep.github.io#142]
In the playground, I hope to support the use of `json` for configuration. I admit that `yaml` is very suitable as a configuration file, but many times I have to carefully consider the indentation of `yaml`, which is very annoying. If it can support the use of `json` as It would be much better to configure

**Comment by HerringtonDarkholme** [comment]
Thanks for the suggestion. There are some issues we need to heed

1. The UI to switch from YAML to JSON and vice-versa. I don't want to clutter the playground page too much.
2. playground URL will store the state of user input. So the new change need to be compatible with URL previously generated.
