### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ast-grep/ast-grep.github.io#187]
By adapting https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

**Comment by HerringtonDarkholme** [comment]
Pull request is welcome.

You can look at the code and get more familiar with https://vitepress.dev/ .

Adding dark theme is not a trivial change now.

**Comment by HerringtonDarkholme** [comment]
fixed. try it online https://ast-grep.github.io/
