### ISSUE TITLE
Failed to resolve import "env" from `ast_grep_wasm`

### ISSUE THREAD

**Issue by SSShuai1999** [ast-grep/ast-grep.github.io#3]
I want to play in the `online playground`. 
I followed `crates/wasm/README.md` and finished step 1 to step 5. 
Then when I run `npm i && npm run dev`, below is the error...

![image](https://user-images.githubusercontent.com/28618801/192262382-d916b7db-5ebf-4fb8-ba49-280037b10026.png)

Did i miss something?

**Comment by SSShuai1999** [comment]
Here is the dependency reference of the js file `pkg/ast_grep_wasm.js` generated with `wasm-bindgen`:

```js
import * as __wbg_star0 from 'env';
import * as __wbg_star1 from 'wasi_snapshot_preview1';
```
Read the related issue:
https://github.com/rustwasm/wasm-bindgen/issues/2215
https://github.com/rustwasm/wasm-bindgen/issues/21

Looks like a different strategy is needed for parsing? I'm not sure.

**OS**
  Win 11.

**Comment by HerringtonDarkholme** [comment]
Hi, you need to first run `wasm-pack build --target=web` and then run `pnpm install`.

The playground repo is not documented yet. The README is more or less a self reminder to me. Sorry for the inconvenience.
