### ISSUE TITLE
Can't reproduce docs output for `Edit` in Python API

### ISSUE THREAD

**Issue by etiennebacher** [ast-grep/ast-grep.github.io#468]
Hi, I'm not sure if I should report this here or in the main repo but I can't reproduce the results from the docs with the 0.24.0 release. In particular, the [example for `Edit`](https://ast-grep.github.io/guide/api-usage/py-api.html#fix-code) in the python API doesn't replace the meta-variables:

```bash
> pip show ast_grep_py
Name: ast-grep-py
Version: 0.24.0
Summary: Structural Search and Rewrite code at large scale using precise AST pattern.
```

```python
from ast_grep_py import SgRoot

root = SgRoot("print('hello world')", "python").root()
node = root.find(pattern="print($A)")
edit = node.replace("logger.log($A)")
new_src = node.commit_edits([edit])
new_src
# 'logger.log($A)'
```
while in the docs this returns `"logger.log('hello world')"`.

**Comment by HerringtonDarkholme** [comment]
Thanks for the report. Python API does not replace metavariable. The doc should be changed.

**Comment by etiennebacher** [comment]
Thanks for the clarification.

> Python API does not replace metavariable

I understand that the python API is still WIP, but will this be possible in the future or is it a hard limitation of the python API?

**Comment by HerringtonDarkholme** [comment]
@etiennebacher not replacing meta variable is not due to technical challenge but rather design. ast-grep's YAML has other configuration like expandStart/expandEnd or various transform object. These things are not necessary in API usage IMHO. Users are encouraged to use their loved programming languages to do string manipulation.
