### ISSUE TITLE
`Field` isn't documented in 'Rule Object Reference'

### ISSUE THREAD

**Issue by soceanainn** [ast-grep/ast-grep.github.io#491]
`Field` isn't documented explicitly on the `Rule Object Reference` page, it's only mentioned in some examples.

This is confusing for readers, and an explicit entry should be added.

**Comment by HerringtonDarkholme** [comment]
Are you talking about `field` in relational rule? It is documented in https://ast-grep.github.io/reference/rule.html#relational-rules
