### ISSUE TITLE
Wrong numbers for bullet points

### ISSUE THREAD

**Issue by etiennebacher** [ast-grep/ast-grep.github.io#497]
In [this section](https://ast-grep.github.io/advanced/language-injection.html#injection-configuration), the numbering of bullet points is broken:

![image](https://github.com/user-attachments/assets/30a42f65-c61e-4961-a628-893590424efb)

**Comment by HerringtonDarkholme** [comment]
fixed!
<img width="783" alt="image" src="https://github.com/user-attachments/assets/78b92ba8-78a5-489a-8e80-694397db6a71">
