### ISSUE TITLE
[bug] incorrect order of arguments in JavaScript API usage example

### ISSUE THREAD

**Issue by apoorvsxna** [ast-grep/ast-grep.github.io#529]
- The API Usage > JavaScript API section on the website contains an example explaining a common workflow.
- The order in which arguments are passed to the `parse` function is incorrect, and needs to be reversed for the code to work right.

Relevant screenshot -

![Screenshot (18)](https://github.com/user-attachments/assets/0cb5e0be-3196-49ef-8683-a8dbae05f910)

**Comment by HerringtonDarkholme** [comment]
Thanks for the report
